#include <stdio.h>

int main() {
    printf("                                          MMMM\n");
    printf("                                       MMMMMMMMMM\n");
    printf("                                     MMMMMMMMMMMMMM\n");
    printf("         MMMM                        MMMMMMMMMMMMMMM\n");
    printf("      MMMMMMMMMM                    MMMMMMMMMMMMMMMM\n");
    printf("     MMMMMMMMMMMM                  MMMMMMMMMMMMMMMMMM\n");
    printf("   MMMMMMMMMMMMMMM                 MMMMMMMMMMMMMMMMMM\n");
    printf("  MMMMMMMMMMMMMMMMM                MMMMMMMMMMMMMMMMMM\n");
    printf("  MMMMMMMMMMMMMMMMM                MMMMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM               MMMMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM               MMMMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM                MMMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM     MMMMMMM    MMMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMM MMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMM  MMMMMMMMM----MMMMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMM MMMMMMMMMM------MMMMMMMMMMMMMM\n");
    printf(" MMMMMMMMMMMMMMMMMMMMM----MMM---/=\\--MMMMMMMMMMMM\n");
    printf("  MMMMMMMMMMMMMMMMMMM--==--MM------\\--MMM MMMMMM\n");
    printf("  MMMMMMMMMMMMMMMMMM--/-----M-------\\--MMM\n");
    printf("   MMMMMMMMMMMMMMMM--/-----------------MMM\n");
    printf("     MMMMMMMMM  MMM--|------------------MMM\n");
    printf("       MMMMM   MMM------/..\\---/..\\-----MMM\n");
    printf("               MMM-----/....\\-/....\\----MMMM\n");
    printf("              MMMM-----......-......----MMMM\n");
    printf("              MMMM-----......-......----MMMM\n");
    printf("              MMMM-----......-.MM...---MMMMM\n");
    printf("              MMMMM----...MM.-.MMM..---MMMMM\n");
    printf("              MMMMM----..MMM.-\\MMM./---MMMMM\n");
    printf("              MMMMMM---\\.MMM.--\\M./---/-----\n");
    printf("              MMMMMM----\\\\M/=======\\---------\n");
    printf("              MM----M--/====-MMMMM------------\n");
    printf("                -----------MMMMMMMM-----------\n");
    printf("               ------------MMMMMMMM-----------\n");
    printf("               ------------MMMMMMMM----X------\n");
    printf("               ------_/----MMMMMMM-----/-\\----\n");
    printf("               -----/\\------MMMMM------|-----\n");
    printf("               ----/--\\---------------/-----\n");
    printf("                -------\\-------------M-----\n");
    printf("                --------=-----------MM----\n");
    printf("                  -------\\=========MMM---\n");
    printf("                   ------MMMMMMMMMMMM---\n");
    printf("                     -----MXXXXXXXXM---\n");
    printf("                    MMMMM--XXXXXXXX--\n");
    printf("                 MMMMMMMMM---XXXX---M\n");
    printf("            MMMMMMMMMMMMMMM--------MMM\n");
    printf("           MMMMMM:++MMMMMMMMM----MMMMM\n");
    printf("          MMMMMM:MMMMMMMMMMMMMMMMMMMMMM\n");
    printf("          MMMMM:M////MMMMMMMMMMMMMMMMMM\n");
    printf("          MMMMM//////////MMMMMMMMMMMMMMM\n");
    printf("          MMMM/////////////MMMMMMMMMMMMM\n");
    printf("          MMM///////////////MMMMMMMMMMMM\n");
    printf("           M///...////////////MMMMMMMMMMM\n");
    printf("           ///....////..///////MMMMMMMMMM\n");
    printf("           ///....///....///////MM  MMMMMM\n");
    printf("           ///....///....////////M  MMMMMM\n");
    printf("          ////...///.....///////// MMMMMMMM\n");
    printf("          ////..////...../////////MMMMMMMMM\n");
    printf("          //////////...../////////MMMMMMMMM\n");
    printf("          //////////....//////////MMMMMMMM\n");
    printf("          ///////////..///////////MMMMMMM\n");
    printf("          ////////////////////////MMMMM\n");
    printf("          ////////////////////////MMM\n");
    printf("           ///////////////////////\n");
    printf("           ///////////////////////\n");
    printf("           ///////////////////////\n");
    printf("           ///////////////////////\n");
    printf("          ////////////////////////\n");
    printf("          ////////////////////////\n");
    printf("          //////X//////////////////\n");
    printf("           //////XXX///////////////\n");
    printf("             ///////V//////////////\n");
    printf("                /////X//////////:::\n");
    printf("                 MMMM/////MMMM::MM\n");
    printf("                  MMMMM|MMMMMMM   MMM\n");
    printf("                  MMMMMM|MMMMMM      MMMM____\n");
    printf("                   MMMMM|MMMMMM              \\------\n");
    printf("                    MMMM\\MMMMMM                     -_\n");
    printf("                     MMMM|MMMMMM                      \\\n");
    printf("                     MMMM\\MMMMMM                       \\\n");
    printf("                      MMMM\\MMMMM                        |\n");
    printf("                       MMM|MMMMMM                      /\n");
    printf("        VVVVVVV      VVMMMM\\MMMMM                     /\n");
    printf("     VVVVVVVVVXVVVV  VVVMMMM|MMMM                   _-\n");
    printf("     VVVVVVVVVVXVVVVVIVVVMMIIMMMMVV            -----\n");
    printf("    VVVVVVVVVVVVVXXVVVIVVVVIIMMMMMVV\n");
    printf("    VVVVVVVVVVVVVVVXXVVVVVVVIIVMMMVVVVVVV\n");
    printf("    VVVVVVVVVVVVVVVVXVXVVVVVIIVVVVVVVVVVVVVVVV\n");
    printf("    VVVVVVVVVVVVVVVVVXVXVVVVIVIVVVVVVVVVVVVXVVVVVV\n");
    printf("    VVVVVVVVVVVVVVVVVVXVXVVIVVVIVVVVVVVVVXVVXVVVVVVV\n");
    printf("     VVVVVVVVVVVVVVVVVVXVXVIVVVVVVVVVVVVXVVXVVVVVVVVV\n");
    printf("     VVVVVVVVVVVVVVVVVVVXVVIVVVVVVVVVVVXVXVVVVVVVVVVVV\n");
    printf("      VVVVVVVVVVVVVVVVVVVVVVIVVVVVVVVVXVXVVVVVVVVVVVVV\n");
    printf("       VVVVVVVVVVVVVVVVVVVVVIVVVVVVVVXVXVVVVVVVVVVVVVV\n");
    printf("         VVVVVVVVVVVVVVVVVV  VVVVVVVXXVVVVVVVVVVVVVVVV\n");
    printf("           VVVVVVVVVVVVVV     VVVXXXVVVVVVVVVVVVVVVVVV\n");
    printf("              VVVVVVVVV        VXVVVVVVVVVVVVVVVVVVVV\n");
    printf("                                 VVVVVVVVVVVVVVVVVVV\n");
    printf("                                  VVVVVVVVVVVVVVVVV\n");
    printf("                                   VVVVVVVVVVVVVV\n");
    printf("                                     VVVVVVVVV\n");
    printf("\n                         Fonte: https://asciiart.cc/view/11448\n");
    
    return 0;
}